### ISSUE TITLE
Container on the page is not affected by render()

### ISSUE THREAD

**Issue by scythargon** [santanubasu/backbone-relational-views#12]
Hello, I'm very glad that you wrote this library, it might be very useful, thank you, but I really can not make it work.
I took the exact code from the first example on your README page, imported all the libraries it depends on, (also, I had to remove require.js wrapper for this demo case), there are no errors in chrome dev console, cv.el and cv.$el is OK - contains rendered templates, BUT $('#somediv') is totally empty. Could you include working example in your source?

**Comment by santanubasu** [comment]
Have you been able to run the demo.html example?  It includes a link to a
bunch of working example code.  These examples show the actual results of
operations side by side with the code used to execute them, and timing
information on how long it takes.  I just did quick test in chrome and saw
that these are still working.  Or are you seeing the same problem running
the sample code as well?

**Comment by scythargon** [comment]
I am able to run `demo.html`, it seem to work as expected, but this one concrete usecase - to render something, is not tested anywhere, in `demo.js` there is `cv.render()` commented out, when `cv` is

``` JavaScript
        cv = new CV({
            model:c,
            el:$("#result")
        });
```

so, when I uncomment this line and go through `demo.html` to this exact test - `$('#result')` is empty again.

**Comment by santanubasu** [comment]
I should probably remove that commented line altogether.  However, I just
tried uncommenting it, and ran the demo again, seems to work fine and
render the result (twice) into the same  element.  If you send me your
modified demo.html, I'd be happy to run it locally and let you know what
result I get.  Also, what version of chrome are you using?  I doubt it's a
browser version issue, but just in case...

**Comment by scythargon** [comment]
I just cloned your repo again, and only uncommented `cv.render()`:( Where exactly do you see doubled result? Because if I run `$("#result")` in chrome console - it returns empty array `[ ]` and if I count lines of text in the left column by hands when the right column says

```
 function that just ran:

function s1800() {
        // Sort a collection containing a large numbers of relational collection elements
        c.get("bb").comparator = bbrv.buildComparator([{path:"value", order:1}]);
        c.get("bb").sort();
        cv.render();
        next = s1900;
    }
```

it is around 1006 in both cases.
My chrome is almost the last version (today I have noticed an update but not installed yet) - `32.0.1700.107` ubuntu 13.10 64-bit.

**Comment by santanubasu** [comment]
Oh what I meant is that the result is rendered twice into the same
container, but there are not twice as many lines.  1006 lines is actually
correct, that is how many I see as well.  So it seems to be working as
expected.

I think I see where the confusion is though.  The way it's coded right now,
when you create a new view like this:

```
    cv = new CV({
        model:c,
        el:$("#result")
    });
```

it will replace the existing element with the rendered version of the view.
 This is done so that views can be recursively rendered, but when child
views aren't changing, they can be used to replace elements that proxy them
in their parent.  This allows very narrow modifications to the middle of a
large dom tree without requiring that all children be re-rendered.

So at the root of a view hierarchy, the replacement is done on the element
specified by $el.  That's why you see $("#result") being empty: it has been
replaced by the rendered result.

**Comment by scythargon** [comment]
Hmmm, that is not the way I expected it to work but OK, I got it, but even given that it still seems to not work: if I add some classes to your templates like this:

```
    var templateA = function(data) {
        return "<div style='position:relative;left:20px' class='templateA'>"+data.this.helperFunction(data.value)+"</div>";
    }

    var templateB = function(data) {
        return "<div style='position:relative;left:20px' class='templateB'>"+data.value+"</div>";
    }

    var templateC = function(data) {
        return "<div style='position:relative;left:20px' class='templateC'><div>"+data.value+"</div>"+data.a+data.bb.join(" ")+data.cc.join(" ")+"</div>";
    }

```

And then on the same step of testing I try `$('.templateA')` or B or C - jquery finds nothing.

**Comment by santanubasu** [comment]
I'm not seeing this behaviour.  I tried adding a class="templateA" and then
breaking at line 191 (inside function s300), and if I check
$(".templateA"), I get a jquery selection with one element in it as I would
expect.  Which line have you put a breakpoint where you are getting the
empty jquery selection?  I can try that out and see what happens.

**Comment by scythargon** [comment]
I just want you you to know that I really appreciate that you answer me.
I have repeated what you did and you are absolutely right.
Hmm and even my previous way to check if such elements exist now shows me a good result. Damn leprechauns. Anyway, thank you a lot:)

Would you be so kind and help a bit more with it? I have made some sample test project with your library and guess what - I could not make it work:) It does not render a thing. Not sure how to send you some files, so I'he uploaded it to dropbox - https://dl.dropboxusercontent.com/u/66817734/bbrv_sample.zip

**Comment by santanubasu** [comment]
No problem, usually I'm pretty busy, but happened to have some spare time
today, so glad to help.  For this example, what seems to be happening here
is that your demo script is running before the DOM is ready, and as a
result the #someDiv doesn't exist yet.  Since you're not using
requires/defines, you'll need to wrap your code in a jquery block that
waits for the document to be ready before it executes.

**Comment by santanubasu** [comment]
Basically, you want to code it something like this (I tested this and it
works):

$(function() {
var templateA = function(data) {
    return "<div style='position:relative;left:20px'
class='A'>"+data.value+"</div>";
}

var templateC = function(data) {
    return "<div style='position:relative;left:20px'
class='C'><div>"+data.value+"</div>"+data.a+"</div>";
}

var A = Backbone.RelationalModel.extend({
    idAttribute:"id"
});

var C = Backbone.RelationalModel.extend({
    idAttribute:"id",
    relations:[
{
    type:Backbone.HasOne,
    key:"a",
    relatedModel: A
}
    ]
});

var AV = Backbone.RelationalView.extend({
    defaultConfig: $.extend(true, {},
Backbone.RelationalView.prototype.defaultConfig, {
template:templateA
    })
});

var CV = Backbone.RelationalView.extend({
    defaultConfig: $.extend(true, {},
Backbone.RelationalView.prototype.defaultConfig, {
template:templateC,
subviewConfigs:{
    a:{
        template:templateA,
        viewType:AV
    }
}
    })
});

var c = new C({
    id:"c1",
    value:"c1",
    a:{
id:"a1",
value:"a1"
    }
});

var cv = new CV({
    model:c,
    el:$("#somediv")
});
});

**Comment by scythargon** [comment]
Oh, seriously?! I've forgot that twice in a twenty-four hours! How I love
JavaScript...
Thank you again! Wish you all the best!:)

2014-02-24 9:23 GMT+06:00 santanubasu notifications@github.com:
